version: 2.1

orbs:
  node: circleci/node@4.2.1
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0

jobs:
  build_deploy:
    executor:
      name: node/default
      tag: '14.6.0'
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build
          command: yarn clean && yarn build
      - run:
          name: Deploy
          command: serverless deploy -v

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_deploy:
          context: deploy
          filters:
            branches:
              only: master
