version: 2.1

orbs:
  node: circleci/node@5.1.0
  # aws-cli: circleci/aws-cli@3.1
  # serverless-framework: circleci/serverless-framework@2.0

jobs:
  build_deploy:
    executor:
      name: node/default
      tag: '16.18.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build
          command: yarn clean && yarn build
      - run:
          name: Update package
          command: npm update undici
      - checkout
      - run: yarn install
      - run:
          name: Configure AWS Credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "aws_default_region=$AWS_DEFAULT_REGION" >> ~/.aws/credentials

      # - run: yarn run lambda:sls setup
      # - checkout
      # - aws-cli/setup
      # - serverless-framework/setup
      - run:
          name: Deploy to AWS Lambda
          command: |
            yarn run lambda:sls deploy
      # - run:
      #     name: Install lambda:sls
      #     command: |
      #       yarn add global @redantinc/lambda-sls
      # - run:
      #     name: Deploy
      #     command: yarn run lambda:sls deploy

  # deploy_app:
  #   docker:
  #     - image: circleci/python:3.8
  #   steps:

workflows:
  build_and_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master
      # - deploy_app:
      #     requires:
      #       - build_deploy
      #     filters:
      #       branches:
      #         only: master
